# fly.toml app configuration file generated for pet-server on 2025-06-06T18:56:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pet-server'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
